Stick to ffmpeg 4.4 to prevent compiler errors around `const AVCodec*`
E.g.
  `streaming/video/ffmpeg.cpp:750:39: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’`

Possibly caused by https://github.com/FFmpeg/FFmpeg/commit/a247ac6