Attempt to fix build error around missing SDL feature
  streaming/video/ffmpeg-renderers/drm.cpp:24:2: error: #error DRM renderer requires SDL built with --enable-video-kmsdrm